version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: challenge-cart-service-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres-cart-service-db:/var/lib/postgresql/data
    networks:
      - app_challenge_cart_service_network

networks:
  app_challenge_cart_service_network:

volumes:
  postgres-cart-service-db:
